import type { Metadata } from "next";
import { Questrial, Rubik } from "next/font/google";

import "swiper/css";
import "swiper/css/pagination";

import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const questrial = Questrial({
  subsets: ["latin"], // Specify subsets you need
  weight: "400", // Available weights for Questrial
});

const rubik = Rubik({
  subsets: ["latin"], // Specify subsets you need
  weight: ["400", "500", "700"], // Available weights for Rubik
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${questrial.className} ${rubik.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
