"use client";
// import type { Metadata } from "next";
import { Questrial, Rubik } from "next/font/google";

import { Provider } from "react-redux";

import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";

import { store } from "./store";

import "swiper/css";
import "swiper/css/pagination";

import "./globals.css";

const questrial = Questrial({
  subsets: ["latin"], // Specify subsets you need
  weight: "400", // Available weights for Questrial
});

const rubik = Rubik({
  subsets: ["latin"], // Specify subsets you need
  weight: ["400", "500", "700"], // Available weights for Rubik
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${questrial.className} ${rubik.className} antialiased`}>
        <Provider store={store}>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
